spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/medical_db
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      platform: postgres
      continue-on-error: true
  h2:
    console:
      enabled: true
server:
  port: 8888

logging:
  level:
    org:
      springframework:
        r2dbc:
          connection:
            init=DEBUG:

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true